### ISSUE TITLE
Replace magrittr pipe with base R pipe

### ISSUE THREAD

**Issue by gvelasq** [gvelasq/tidytab#18]

**Comment by askawron** [comment]
Hi,
just to be sure, you need to replace the pipe %>% by the native R pipe |> in all R codes?
I would be happy to contribute.

**Comment by gvelasq** [comment]
@askawron, thank you for offering to contribute. The task is to remove the magrittr pipe entirely from the package, which would involve:

- Replace the `%>%` pipe with `|>` in all instances.
- Remove mention of the magrittr pipe (e.g., in the first example in the README, and anywhere else I may mention that the tidytab exports the magrittr pipe).
- Remove utils-pipe.R such that `%>%` is no longer exported.
- [`devtools::load_all()`](https://r-pkgs.org/workflow101.html#sec-workflow101-load-all) and [`devtools::document()`](https://r-pkgs.org/man.html#sec-man-workflow) the package which will rebuild NAMESPACE and other files.
